version: "3"
services:
    dob-consumer:
      build:
        context: consumer/.
        dockerfile: Dockerfile
      ports:
        - "80:5000"
      networks:
        - default
    dob-producer:
      build:
        context: producer/.
        dockerfile: Dockerfile
      networks:
        - default
    dob-storage:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: Exam-2021
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        volumes:
            - ./storage/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        ports:
          - "3306:3306"
        networks:
          - default
